### ISSUE TITLE
Windows compatibility?

### ISSUE THREAD

**Issue by 8ctopus** [talhasch/php-httpstat#1]
Just discovered your php implementation of reorx's httpstat unfortunately it's not compatible with Windows as the posix module is (not available on Windows)[https://www.php.net/manual/en/intro.posix.php].

```
71 $ISATTY = posix_isatty(STDOUT);
```

```
Luna@Roxy MINGW64 /k/dev/github/php-httpstat (master)
$ php httpstat.php https://tass.ru
PHP Fatal error:  Uncaught Error: Call to undefined function posix_isatty() in K:\dev\github\php-httpstat\httpstat.php:71
Stack trace:
#0 {main}
  thrown in K:\dev\github\php-httpstat\httpstat.php on line 71

Fatal error: Uncaught Error: Call to undefined function posix_isatty() in K:\dev\github\php-httpstat\httpstat.php on line 71

Error: Call to undefined function posix_isatty() in K:\dev\github\php-httpstat\httpstat.php on line 71

Call Stack:
    0.4125     461880   1. {main}() K:\dev\github\php-httpstat\httpstat.php:0
```

Solving that problem, leads to other problems further down.

**Comment by talhasch** [comment]
Thanks for reporting @8ctopus I will try to fix this issue soon.

**Comment by 8ctopus** [comment]
@talhasch wow that was fast 👍

I spent some time to fix the Windows problems I was experiencing, please find them in #2

**Comment by talhasch** [comment]
@8ctopus  Merged to master. Thanks for your efforts!

**Comment by 8ctopus** [comment]
@talhasch thank you for taking the time to review again.
